"""Generate a self-contained Kaggle notebook that fills in the missing table row.

The notebook embeds the current contents of `defectloc/` as strings and writes
them back out on the Kaggle side, so the run uses exactly the code in this repo
with no GitHub remote and no manual copy-paste. Regenerate it after any change
to the package.

    python scripts/make_kaggle_kernel.py

Writes kaggle_kernel/ (notebook + kernel-metadata.json), which is what
`kaggle kernels push -p kaggle_kernel` uploads.
"""

import argparse
import json
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]

# Embedded verbatim so the Kaggle run matches this repo exactly.
PACKAGE_FILES = [
    "defectloc/__init__.py",
    "defectloc/config.py",
    "defectloc/model.py",
    "defectloc/losses.py",
    "defectloc/data.py",
    "defectloc/augment.py",
    "defectloc/anomaly.py",
    "defectloc/train.py",
    "defectloc/evaluate.py",
    "defectloc/visualize.py",
]


def md(text):
    return {"cell_type": "markdown", "metadata": {}, "source": text.splitlines(keepends=True)}


def code(text):
    return {
        "cell_type": "code",
        "metadata": {},
        "execution_count": None,
        "outputs": [],
        "source": text.splitlines(keepends=True),
    }


def build_notebook(category: str, epochs: int, seed: int) -> dict:
    sources = {p: (REPO / p).read_text(encoding="utf-8") for p in PACKAGE_FILES}

    cells = [
        md(
            "# Fill the median/MAD row — bottle defect localisation\n"
            "\n"
            "Generated by `scripts/make_kaggle_kernel.py`. Do not edit here; edit the repo and\n"
            "regenerate, otherwise the Kaggle run and the repo drift apart.\n"
            "\n"
            "Trains the v3 autoencoder and evaluates it on the clean and lighting-stressed test\n"
            "sets, scoring both ways (raw top-k, and median/MAD-normalised) in one pass over\n"
            "identical anomaly maps.\n"
            "\n"
            "**Settings this notebook needs:** GPU accelerator, Internet on (for one `pip install`),\n"
            "and the `ipythonx/mvtec-ad` dataset attached.\n"
        ),
        code(
            "!pip install -q pytorch-msssim\n"
            "import torch, sys\n"
            "print('torch', torch.__version__, '| cuda', torch.cuda.is_available())\n"
            "print('device:', torch.cuda.get_device_name(0) if torch.cuda.is_available() else 'CPU')\n"
        ),
        md("## 1. Write the package\n\nThe repo's modules, embedded verbatim at generation time.\n"),
    ]

    # One cell writing every module, using an explicit delimiter rather than
    # nested triple quotes (module docstrings would otherwise close the string).
    writer = [
        "import os, base64, pathlib\n",
        "os.makedirs('/kaggle/working/defectloc', exist_ok=True)\n",
        "FILES = {\n",
    ]
    for path, src in sources.items():
        b64 = __import__("base64").b64encode(src.encode("utf-8")).decode("ascii")
        writer.append(f"    {path!r}: {b64!r},\n")
    writer += [
        "}\n",
        "for path, blob in FILES.items():\n",
        "    p = pathlib.Path('/kaggle/working') / path\n",
        "    p.parent.mkdir(parents=True, exist_ok=True)\n",
        "    p.write_bytes(base64.b64decode(blob))\n",
        "sys.path.insert(0, '/kaggle/working')\n",
        "print('wrote', len(FILES), 'modules')\n",
    ]
    cells.append(code("".join(writer)))

    cells += [
        md(
            "## 2. Locate the dataset\n"
            "\n"
            "Searches the attached inputs instead of hardcoding a path. The hardcoded\n"
            "`DATA_ROOT` is what broke the original notebook when the mount point changed.\n"
        ),
        code(
            "import pathlib\n"
            f"CATEGORY = {category!r}\n"
            "\n"
            "candidates = [p.parent for p in pathlib.Path('/kaggle/input').glob(f'**/{CATEGORY}/train/good')]\n"
            "if not candidates:\n"
            "    raise SystemExit(\n"
            "        f'no {CATEGORY}/train/good under /kaggle/input.\\n'\n"
            "        'Attach the ipythonx/mvtec-ad dataset via + Add Input.'\n"
            "    )\n"
            "SRC_ROOT = candidates[0].parent\n"
            "print('dataset root:', SRC_ROOT)\n"
            "print('categories visible:', sorted(p.name for p in SRC_ROOT.iterdir() if p.is_dir())[:20])\n"
        ),
        md(
            "## 3. Build the clean and lighting-stressed roots\n"
            "\n"
            "The lighting stress test is seeded, so this is the same set of images every run.\n"
        ),
        code(
            "import shutil, cv2, pathlib\n"
            "from defectloc.augment import build_factory_lighting\n"
            "\n"
            f"SEED = {seed}\n"
            "CLEAN = pathlib.Path('/kaggle/working/data/MVTecAD') / CATEGORY\n"
            "LIGHT = pathlib.Path('/kaggle/working/data/MVTecAD_lighting') / CATEGORY\n"
            "\n"
            "if not CLEAN.exists():\n"
            "    shutil.copytree(SRC_ROOT / CATEGORY, CLEAN)\n"
            "print('clean:', CLEAN, '| train imgs:', len(list((CLEAN / 'train' / 'good').glob('*.png'))))\n"
            "\n"
            "if not LIGHT.exists():\n"
            "    lighting = build_factory_lighting(seed=SEED)\n"
            "    n = 0\n"
            "    for split in sorted((CLEAN / 'test').iterdir()):\n"
            "        if not split.is_dir():\n"
            "            continue\n"
            "        for img_path in sorted(split.glob('*.png')):\n"
            "            img = cv2.cvtColor(cv2.imread(str(img_path)), cv2.COLOR_BGR2RGB)\n"
            "            aug = cv2.cvtColor(lighting(image=img)['image'], cv2.COLOR_RGB2BGR)\n"
            "            out = LIGHT / 'test' / split.name / img_path.name\n"
            "            out.parent.mkdir(parents=True, exist_ok=True)\n"
            "            cv2.imwrite(str(out), aug)\n"
            "            n += 1\n"
            "    shutil.copytree(CLEAN / 'ground_truth', LIGHT / 'ground_truth', dirs_exist_ok=True)\n"
            "    shutil.copytree(CLEAN / 'train', LIGHT / 'train', dirs_exist_ok=True)\n"
            "    print(f'lighting: {LIGHT} ({n} test images stressed, seed={SEED})')\n"
        ),
        md("## 4. Train\n\nSame architecture, loss and objective as v3.\n"),
        code(
            "import time\n"
            "from defectloc.config import Config\n"
            "from defectloc.train import train, save_checkpoint, pick_device\n"
            "\n"
            f"cfg = Config(epochs={epochs}, seed=SEED, num_workers=2)\n"
            "device = pick_device('auto')\n"
            "t0 = time.time()\n"
            "model, history = train(CLEAN, cfg, device, log_every=10)\n"
            "elapsed = time.time() - t0\n"
            "ckpt = save_checkpoint('/kaggle/working/checkpoints/ae_v3.pt', model, cfg, history,\n"
            "                       extra={'data_root': str(CLEAN), 'train_seconds': round(elapsed, 1),\n"
            "                              'device': str(device)})\n"
            "print(f'trained in {elapsed:.1f}s -> {ckpt}')\n"
        ),
        md(
            "## 5. Look at the maps before reading the metric\n"
            "\n"
            "A pixel-AUROC can look respectable while the map fires on rims and reflections\n"
            "instead of the defect. Inspect first.\n"
        ),
        code(
            "from defectloc.visualize import make_figure\n"
            "make_figure(model, cfg, CLEAN, device, n=3,\n"
            "            out='/kaggle/working/results/figures/v3_clean.png')\n"
            "make_figure(model, cfg, LIGHT, device, n=3,\n"
            "            out='/kaggle/working/results/figures/v3_lighting.png')\n"
            "from IPython.display import Image, display\n"
            "display(Image('/kaggle/working/results/figures/v3_clean.png'))\n"
            "display(Image('/kaggle/working/results/figures/v3_lighting.png'))\n"
        ),
        md(
            "## 6. Evaluate\n"
            "\n"
            "Both scoring variants, one pass, identical maps. `median_mad` under `lighting` is\n"
            "the number the results table is missing.\n"
        ),
        code(
            "import json\n"
            "from defectloc.evaluate import evaluate, SCORE_VARIANTS\n"
            "\n"
            "run = {'label': 'Autoencoder v3', 'checkpoint': str(ckpt), 'config': cfg.to_dict(),\n"
            "       'train_seconds': round(elapsed, 1),\n"
            "       'final_train_loss': history[-1]['loss'],\n"
            "       'environment': {'device': str(device), 'torch': torch.__version__,\n"
            "                       'ran_on': 'kaggle'},\n"
            "       'conditions': {}}\n"
            "\n"
            "for name, root in (('clean', CLEAN), ('lighting', LIGHT)):\n"
            "    res = evaluate(model, root, cfg, device, batch_size=8)\n"
            "    res['root'] = str(root)\n"
            "    run['conditions'][name] = res\n"
            "    for v in SCORE_VARIANTS:\n"
            "        m = res['variants'][v]\n"
            "        print(f\"{name:9s} [{v:10s}]  image-AUROC {m['image_AUROC']:.4f}\"\n"
            "              f\"   pixel-AUROC {m['pixel_AUROC']:.4f}\")\n"
            "\n"
            "import pathlib\n"
            "out = pathlib.Path('/kaggle/working/results/runs/ae_v3_kaggle.json')\n"
            "out.parent.mkdir(parents=True, exist_ok=True)\n"
            "out.write_text(json.dumps(run, indent=2))\n"
            "print('\\nwrote', out)\n"
        ),
        md("## 7. The row, and whether the fix worked\n"),
        code(
            "raw_l = run['conditions']['lighting']['variants']['none']['image_AUROC']\n"
            "nrm_l = run['conditions']['lighting']['variants']['median_mad']['image_AUROC']\n"
            "raw_c = run['conditions']['clean']['variants']['none']['image_AUROC']\n"
            "nrm_c = run['conditions']['clean']['variants']['median_mad']['image_AUROC']\n"
            "print(f'lighting image-AUROC: raw {raw_l:.3f} -> median/MAD {nrm_l:.3f} '\n"
            "      f'({nrm_l - raw_l:+.3f})')\n"
            "print(f'clean    image-AUROC: raw {raw_c:.3f} -> median/MAD {nrm_c:.3f} '\n"
            "      f'({nrm_c - raw_c:+.3f})')\n"
            "print()\n"
            "print('chance is 0.500. The fix is only a win if lighting image-AUROC rises well')\n"
            "print('clear of chance WITHOUT costing much on clean. A clean drop is a real cost,')\n"
            "print('not a rounding detail: report it either way.')\n"
        ),
    ]

    return {
        "cells": cells,
        "metadata": {
            "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
            "language_info": {"name": "python"},
        },
        "nbformat": 4,
        "nbformat_minor": 4,
    }


def main(argv=None) -> int:
    p = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    p.add_argument("--username", default="YOUR_KAGGLE_USERNAME",
                   help="Kaggle username; required by kernel-metadata.json before pushing")
    p.add_argument("--slug", default="bottle-defect-mad-score")
    p.add_argument("--category", default="bottle")
    p.add_argument("--epochs", type=int, default=80)
    p.add_argument("--seed", type=int, default=0)
    p.add_argument("--out-dir", default="kaggle_kernel")
    p.add_argument("--public", action="store_true",
                   help="publish the kernel publicly (default: private)")
    a = p.parse_args(argv)

    out_dir = REPO / a.out_dir
    out_dir.mkdir(parents=True, exist_ok=True)
    nb_name = f"{a.slug}.ipynb"

    (out_dir / nb_name).write_text(
        json.dumps(build_notebook(a.category, a.epochs, a.seed), indent=1), encoding="utf-8"
    )

    metadata = {
        "id": f"{a.username}/{a.slug}",
        "title": "Bottle defect localisation - median/MAD score",
        "code_file": nb_name,
        "language": "python",
        "kernel_type": "notebook",
        "is_private": not a.public,
        "enable_gpu": True,
        "enable_internet": True,
        "dataset_sources": ["ipythonx/mvtec-ad"],
        "competition_sources": [],
        "kernel_sources": [],
    }
    (out_dir / "kernel-metadata.json").write_text(json.dumps(metadata, indent=2), encoding="utf-8")

    print(f"wrote {out_dir / nb_name}")
    print(f"wrote {out_dir / 'kernel-metadata.json'}")
    if a.username == "YOUR_KAGGLE_USERNAME":
        print("\nSet a real username before pushing:")
        print(f"  python scripts/make_kaggle_kernel.py --username <your-kaggle-username>")
    else:
        print(f"\n  kaggle kernels push -p {a.out_dir}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
